use DataScience_SQL;

-- What is the total sales?
SELECT SUM(Sales_Amount)
FROM Sales;

SELECT SUM(Sales_Amount) AS Total_Sales
FROM Sales;

-- COUNT() counts records.
SELECT COUNT(*) AS Total_Sales_Transactions
FROM Sales;

-- AVG() calculates the average.
SELECT AVG(Sales_Amount) AS Average_Sale
FROM Sales;


--Find the smallest value.
SELECT MIN(Sales_Amount) AS Minimum_Sale
FROM Sales;

--Find the largest value.
SELECT MAX(Sales_Amount) AS Maximum_Sale
FROM Sales;

--Multiple Aggregate Functions Together
SELECT
    SUM(Sales_Amount) AS Total_Sales,
    COUNT(*) AS Total_Transactions,
    AVG(Sales_Amount) AS Average_Sale,
    MIN(Sales_Amount) AS Minimum_Sale,
    MAX(Sales_Amount) AS Maximum_Sale
FROM Sales;


-- Group by 
-- group by used to group the similer rows and gives the result
SELECT
    Customer_ID,
    SUM(Sales_Amount) AS Total_Sales
FROM Sales
GROUP BY Customer_ID;


--How many sales transactions did each customer make?
SELECT
    Customer_ID,
    COUNT(*) AS Number_of_Sales
FROM Sales
GROUP BY Customer_ID;

--What is the average transaction value for each customer?
SELECT
    Customer_ID,
    AVG(Sales_Amount) AS Average_Sale
FROM Sales
GROUP BY Customer_ID;

SELECT
    Customer_ID,
    MIN(Sales_Amount) AS Minimum_Sale,
    MAX(Sales_Amount) AS Maximum_Sale
FROM Sales
GROUP BY Customer_ID;


--GROUP BY Multiple Columns
-- group by more than one column.
--Group sales by customer AND product.
SELECT
    Customer_ID,
    Product_ID,
    SUM(Sales_Amount) AS Total_Sales
FROM Sales
GROUP BY Customer_ID, Product_ID;


--we want customers with the highest sales first:
SELECT
    Customer_ID,
    SUM(Sales_Amount) AS Total_Sales
FROM Sales
GROUP BY Customer_ID
ORDER BY Total_Sales DESC;



-- Task 1
-- Find the:
-- Total quantity of products sold.
SELECT
    SUM(Quantity) AS Total_Quantity
FROM Sales;

--Task 2
--Find:
--Total number of sales transactions.
select count(*) as total_sales_transactions from Sales;

--Task 3
--Find:
--Average quantity per transaction.
SELECT
    AVG(Quantity) AS Average_Quantity_Per_Transaction
FROM Sales;

--Task 4
--Find:
--Highest quantity sold in a single transaction.
SELECT
    MAX(Quantity) AS Highest_Quantity_Sold_In_Single_Transaction
FROM Sales;

--Task 5
--Find:
--Lowest sales amount.
select MIN(Sales_Amount) as Lowest_sales_amount from Sales;

--Task 6
--Find:
--Total sales amount for each customer.
--Expected columns:
--Customer_ID
--Total_Sales
select
        Customer_ID , 
		sum(Sales_Amount) as Total_Sales 
from Sales 
group by Customer_ID;

--Task 7
--Find:
--Number of transactions made by each customer.
--Expected:
--Customer_ID
--Number_of_Transactions
select
        Customer_ID , 
		count(Sales_Amount) as Number_of_Transactions 
from Sales 
group by Customer_ID;

--Task 8
--Find:
--Average sales amount for each customer.
select
        Customer_ID , 
		avg(Sales_Amount) as Average_sales_amount 
from Sales 
group by Customer_ID;

--Task 9
--Find:
--Total revenue generated by each product.
--Expected:
--Product_ID
--Total_Revenue
SELECT
    Product_ID,
    SUM(Sales_Amount) AS Total_Revenue
FROM Sales
GROUP BY Product_ID;

--Task 10
--Find:
--Total quantity sold for each product.
--Expected:
--Product_ID
--Total_Quantity
SELECT
    Product_ID,
    SUM(Quantity) AS Total_Quantity
FROM Sales
GROUP BY Product_ID;


--Task 11
--Find:
--Customers ordered by total spending, highest first.
--Expected:
--Customer_ID
--Total_Spending
SELECT 
    Customer_ID,
    SUM(Sales_Amount) AS Total_Spending
FROM Sales
GROUP BY Customer_ID
ORDER BY Total_Spending DESC;





--BUSINESS CHALLENGE
--"Which customers generated the most revenue?"
select 
      Customer_ID ,
	  SUM(Sales_Amount) as most_revenue 
from Sales
group by Customer_ID
order by most_revenue desc;
